title: Quote Service
email: qs-devs@ovoenergy.com
description: Quote service
organisation: stuartizon #ovoenergy
baseurl: /test-docs

# Build settings
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock